/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListasRouteImport } from './routes/listas'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FiltrosRouteImport } from './routes/filtros'
import { Route as FilmesRouteImport } from './routes/filmes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CarregandoRouteImport } from './routes/carregando'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SerieIdRouteImport } from './routes/serie.$id'
import { Route as DetalhesIdRouteImport } from './routes/detalhes.$id'

const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListasRoute = ListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltrosRoute = FiltrosRouteImport.update({
  id: '/filtros',
  path: '/filtros',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesRoute = FilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarregandoRoute = CarregandoRouteImport.update({
  id: '/carregando',
  path: '/carregando',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieIdRoute = SerieIdRouteImport.update({
  id: '/serie/$id',
  path: '/serie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DetalhesIdRoute = DetalhesIdRouteImport.update({
  id: '/detalhes/$id',
  path: '/detalhes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canais': typeof CanaisRoute
  '/carregando': typeof CarregandoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/filmes': typeof FilmesRoute
  '/filtros': typeof FiltrosRoute
  '/home': typeof HomeRoute
  '/listas': typeof ListasRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRoute
  '/series': typeof SeriesRoute
  '/detalhes/$id': typeof DetalhesIdRoute
  '/serie/$id': typeof SerieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canais': typeof CanaisRoute
  '/carregando': typeof CarregandoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/filmes': typeof FilmesRoute
  '/filtros': typeof FiltrosRoute
  '/home': typeof HomeRoute
  '/listas': typeof ListasRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRoute
  '/series': typeof SeriesRoute
  '/detalhes/$id': typeof DetalhesIdRoute
  '/serie/$id': typeof SerieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canais': typeof CanaisRoute
  '/carregando': typeof CarregandoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/filmes': typeof FilmesRoute
  '/filtros': typeof FiltrosRoute
  '/home': typeof HomeRoute
  '/listas': typeof ListasRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRoute
  '/series': typeof SeriesRoute
  '/detalhes/$id': typeof DetalhesIdRoute
  '/serie/$id': typeof SerieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canais'
    | '/carregando'
    | '/configuracoes'
    | '/filmes'
    | '/filtros'
    | '/home'
    | '/listas'
    | '/login'
    | '/player'
    | '/series'
    | '/detalhes/$id'
    | '/serie/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canais'
    | '/carregando'
    | '/configuracoes'
    | '/filmes'
    | '/filtros'
    | '/home'
    | '/listas'
    | '/login'
    | '/player'
    | '/series'
    | '/detalhes/$id'
    | '/serie/$id'
  id:
    | '__root__'
    | '/'
    | '/canais'
    | '/carregando'
    | '/configuracoes'
    | '/filmes'
    | '/filtros'
    | '/home'
    | '/listas'
    | '/login'
    | '/player'
    | '/series'
    | '/detalhes/$id'
    | '/serie/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanaisRoute: typeof CanaisRoute
  CarregandoRoute: typeof CarregandoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FilmesRoute: typeof FilmesRoute
  FiltrosRoute: typeof FiltrosRoute
  HomeRoute: typeof HomeRoute
  ListasRoute: typeof ListasRoute
  LoginRoute: typeof LoginRoute
  PlayerRoute: typeof PlayerRoute
  SeriesRoute: typeof SeriesRoute
  DetalhesIdRoute: typeof DetalhesIdRoute
  SerieIdRoute: typeof SerieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listas': {
      id: '/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof ListasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filtros': {
      id: '/filtros'
      path: '/filtros'
      fullPath: '/filtros'
      preLoaderRoute: typeof FiltrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes': {
      id: '/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof FilmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carregando': {
      id: '/carregando'
      path: '/carregando'
      fullPath: '/carregando'
      preLoaderRoute: typeof CarregandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/$id': {
      id: '/serie/$id'
      path: '/serie/$id'
      fullPath: '/serie/$id'
      preLoaderRoute: typeof SerieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detalhes/$id': {
      id: '/detalhes/$id'
      path: '/detalhes/$id'
      fullPath: '/detalhes/$id'
      preLoaderRoute: typeof DetalhesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanaisRoute: CanaisRoute,
  CarregandoRoute: CarregandoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FilmesRoute: FilmesRoute,
  FiltrosRoute: FiltrosRoute,
  HomeRoute: HomeRoute,
  ListasRoute: ListasRoute,
  LoginRoute: LoginRoute,
  PlayerRoute: PlayerRoute,
  SeriesRoute: SeriesRoute,
  DetalhesIdRoute: DetalhesIdRoute,
  SerieIdRoute: SerieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
